# Dockerfile for rasa server, compatible with macos M1 chip

# Apple M1 chip compatible Dockerfile with rasa 3.1.0 based on https://github.com/khalo-sa/rasa-apple-silicon
FROM svenvanderburg/rasa-apple-silicon:3.1.0

# Change to root user to install dependencies
USER root

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git gcc python3-dev libxml2-dev libxslt1-dev zlib1g-dev g++

# Install requirements, do not install rasa
COPY requirements.txt .
RUN pip install $(grep -ivE "^rasa|^#|^\s*$" requirements.txt | sed s/#.*//g)

# Necessary because of
# https://stackoverflow.com/questions/66060487/valueerror-numpy-ndarray-size-changed-may-indicate-binary-incompatibility-exp
RUN python -m pip install --upgrade numpy

# Use subdirectory as working directory
WORKDIR /app

COPY . /app

RUN chmod -R 777 /app

# Don't use root user to run code
USER 1001

ENTRYPOINT ["rasa", "run", "--enable-api"]
