"""empty message

Revision ID: d77ec0c12a5f
Revises: 7e1f07178ecd
Create Date: 2021-08-25 13:15:12.509095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd77ec0c12a5f'
down_revision = '7e1f07178ecd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nicedayuid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'nicedayuid')
    # ### end Alembic commands ###
