"""empty message

Revision ID: 47fdbb6df646
Revises: 0fbd84da495e
Create Date: 2021-05-06 09:48:51.044217

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '47fdbb6df646'
down_revision = '0fbd84da495e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    op.drop_column('users', 'age')
    # ### end Alembic commands ###
